"""
Generate production-ready INSERT SQL for voter_records from OCR parse cache.

Usage:
    python scripts/generate_voter_import_sql.py

Output:
    data/seed/005_voters_part1.sql  — INSERT statements for Booth 001 voters
"""
from __future__ import annotations

import json
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.voter_roll_ingestion.normalizer import normalize_batch
from app.voter_roll_ingestion.parser import parse_document

# Paths
OCR_CACHE = Path("data/ocr_cache/part1_cols_ocr.json")
OUT_SQL = Path("data/seed/005_voters_part1.sql")

CONSTITUENCY_ID = "11111111-0052-4000-8000-000000000001"
PART_NUMBER = 1

HEADER = f"""-- ================================================================
-- Seed: Real ECI Voter Records — Part 1 (GHMC Ward Office, Rai Darga)
-- Source: Electoral Roll 2025 S29 Telangana, AC-52, Part 1
-- Booth: booth_number='001' in constituencies UUID {CONSTITUENCY_ID}
-- Generated by scripts/generate_voter_import_sql.py
-- NOTE: Inserts to 'voters' table using ON CONFLICT DO NOTHING
-- ================================================================

DO $$
DECLARE
    v_booth_id UUID;
BEGIN
    SELECT id INTO v_booth_id
    FROM booths
    WHERE constituency_id = '{CONSTITUENCY_ID}'::UUID
      AND booth_number = '{str(PART_NUMBER).zfill(3)}';

    IF v_booth_id IS NULL THEN
        RAISE EXCEPTION 'Booth 001 not found — run 004_real_booth_part1.sql first';
    END IF;

"""

FOOTER = """
    RAISE NOTICE 'Part 1 voter insert complete';
END;
$$;
"""


def escape_sql(val) -> str:
    if val is None:
        return "NULL"
    s = str(val).replace("'", "''")
    return f"'{s}'"


def main() -> None:
    if not OCR_CACHE.exists():
        print(f"ERROR: OCR cache not found: {OCR_CACHE}", file=sys.stderr)
        sys.exit(1)

    cache = json.loads(OCR_CACHE.read_text(encoding="utf-8"))
    pages = [(item[0], item[1]) for item in cache]
    doc = parse_document(pages)
    valid, invalid = normalize_batch(doc.voters)

    print(f"Parsed: {len(doc.voters)} raw | {len(valid)} valid | {invalid} invalid")

    lines = [HEADER]
    lines.append("    INSERT INTO voters\n"
                 "        (id, booth_id, voter_id, serial_number, full_name, father_name,\n"
                 "         gender, age, is_contacted, created_at)\n"
                 "    VALUES")

    value_rows = []
    for v in valid:
        row_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"AC52-PART1-{v.ec_voter_id}"))
        value_rows.append(
            f"        ({escape_sql(row_id)}, v_booth_id, {escape_sql(v.ec_voter_id)}, "
            f"{v.serial_number if v.serial_number is not None else 'NULL'}, "
            f"{escape_sql(v.name)}, {escape_sql(v.father_or_husband_name)}, "
            f"{escape_sql(v.gender)}, "
            f"{v.age if v.age is not None else 'NULL'}, "
            f"FALSE, NOW())"
        )

    lines.append(",\n".join(value_rows))
    lines.append("    ON CONFLICT (voter_id) DO NOTHING;")
    lines.append(FOOTER)

    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {OUT_SQL} ({OUT_SQL.stat().st_size:,} bytes, {len(valid)} voter rows)")


if __name__ == "__main__":
    main()
