#!/usr/bin/env python3
"""
Generate booth seed SQL for Serilingampally AC-52.

This script creates 315 booths distributed across 7 zones with
realistic coordinates derived from the PRD zone specifications.

Usage:
    python scripts/generate_booth_seed.py > data/seed/003_booths.sql

When real ECI booth data arrives, run scripts/import_booths_csv.py instead.
"""
import random
import uuid

# Zone definitions: (zone_id, zone_code, zone_name, booth_count, center_lat, center_lng, spread)
ZONES = [
    ("22222222-0001-4000-8000-000000000001", "Z-01", "Kondapur Zone",   55, 17.470, 78.362, 0.012),
    ("22222222-0002-4000-8000-000000000002", "Z-02", "Madhapur Zone",   48, 17.449, 78.392, 0.010),
    ("22222222-0003-4000-8000-000000000003", "Z-03", "Gachibowli Zone", 42, 17.441, 78.349, 0.011),
    ("22222222-0004-4000-8000-000000000004", "Z-04", "HITEC City Zone", 38, 17.451, 78.381, 0.009),
    ("22222222-0005-4000-8000-000000000005", "Z-05", "Hafeezpet Zone",  52, 17.491, 78.337, 0.012),
    ("22222222-0006-4000-8000-000000000006", "Z-06", "Chandanagar Zone",45, 17.498, 78.312, 0.011),
    ("22222222-0007-4000-8000-000000000007", "Z-07", "Nallagandla Zone",35, 17.461, 78.323, 0.010),
]

CONSTITUENCY_ID = "11111111-0052-4000-8000-000000000001"

# Booth name templates per zone
BOOTH_NAMES = {
    "Z-01": [
        "Kondapur Primary School", "Ayyappa Society Community Hall", "Laxmi Cyber City PS",
        "Sri Ramana PS Kondapur", "JNTU Hyderabad PS", "Sai Nagar PS", "Cyber Towers PS",
        "DLF Cyber Hub PS", "Kondapur GHMC Office PS", "Puppalaguda PS",
    ],
    "Z-02": [
        "Madhapur PS", "Jubilee Hills Road PS", "Raidurg PS", "Film Nagar PS",
        "Leela Palace PS", "Inorbit Mall PS", "Madhapur Police Colony PS",
        "HITEC City Road PS", "Kavuri Hills PS", "Road No 36 PS",
    ],
    "Z-03": [
        "Gachibowli Stadium PS", "Financial District PS", "ISB Road PS",
        "DLF Building PS", "IIIT Hyderabad PS", "Wipro Circle PS",
        "Khajaguda PS", "Manikonda PS", "Nanakramguda PS", "Gachibowli Layout PS",
    ],
    "Z-04": [
        "HITEC City GHMC PS", "Whitefields PS", "Kothaguda PS",
        "Cyber Pearl PS", "Raheja Mindspace PS", "Madhapur Police Station PS",
        "Vittal Rao Nagar PS", "Ambedkar Nagar PS", "HUDA Bhavan PS",
    ],
    "Z-05": [
        "Hafeezpet PS", "Miyapur Link Road PS", "RC Puram PS",
        "Balkampet Road PS", "Serilingampally Mandal PS", "Balanagar PS",
        "Kukatpally Border PS", "Nizampet PS", "SR Nagar PS", "Moosapet PS",
    ],
    "Z-06": [
        "Chandanagar PS", "Lingampally PS", "OFB Chanda Nagar PS",
        "Prashasan Nagar PS", "Beeramguda PS", "BHEL PS",
        "Patancheru Bypass PS", "Ramachandrapuram PS", "Gandipet PS",
    ],
    "Z-07": [
        "Nallagandla PS", "Tellapur PS", "Kollur PS",
        "Osman Sagar Road PS", "Narsingi PS", "Aparna Sarovar PS",
        "Puppalaguda Hills PS", "Rajapushpa PS", "Shankarpalli Road PS",
    ],
}

SWING_BOOTH_PROBABILITY = 0.12


def make_catchment(lat: float, lng: float, size: float = 0.003) -> dict:
    """Generate a simple catchment polygon around a booth point."""
    h = size / 2
    return {
        "type": "Polygon",
        "coordinates": [[
            [lng - h, lat - h],
            [lng + h, lat - h],
            [lng + h, lat + h],
            [lng - h, lat + h],
            [lng - h, lat - h],
        ]],
    }


def generate():
    random.seed(42)
    lines = [
        "-- ============================================================",
        "-- Seed: Booths — Serilingampally AC-52 (315 booths)",
        "-- Generated by scripts/generate_booth_seed.py",
        "-- Replace with real ECI data via scripts/import_booths_csv.py",
        "-- ============================================================",
        "DO $$",
        "DECLARE",
        f"    v_cid UUID := '{CONSTITUENCY_ID}';",
        "BEGIN",
        "",
        "INSERT INTO booths (id, constituency_id, zone_id, booth_number, booth_name,",
        "    location, address, total_voters, female_voters, male_voters,",
        "    swing_booth, risk_score, health_score, contact_rate)",
        "VALUES",
    ]

    booth_number = 1
    rows = []

    for zone_id, zone_code, zone_name, count, center_lat, center_lng, spread in ZONES:
        names = BOOTH_NAMES[zone_code]
        for i in range(count):
            b_id = str(uuid.uuid4())
            lat = center_lat + random.uniform(-spread, spread)
            lng = center_lng + random.uniform(-spread, spread)
            total_v = random.randint(700, 1400)
            female_v = int(total_v * random.uniform(0.44, 0.52))
            male_v = total_v - female_v
            swing = random.random() < SWING_BOOTH_PROBABILITY
            risk = round(random.uniform(20, 70), 2)
            health = round(random.uniform(30, 80), 2)
            contact = round(random.uniform(0, 45), 2)
            name_idx = i % len(names)
            suffix = f" {i // len(names) + 1}" if i >= len(names) else ""
            booth_name = names[name_idx] + suffix

            geom = f"ST_GeogFromText('SRID=4326;POINT({lng:.6f} {lat:.6f})')"
            address = f"{booth_name}, {zone_name.replace(' Zone', '')}, Serilingampally, Hyderabad"

            rows.append(
                f"    ('{b_id}', v_cid, '{zone_id}', '{booth_number:03d}', "
                f"'{booth_name.replace(chr(39), chr(39)+chr(39))}',\n"
                f"     {geom}, "
                f"'{address.replace(chr(39), chr(39)+chr(39))}', "
                f"{total_v}, {female_v}, {male_v},\n"
                f"     {'TRUE' if swing else 'FALSE'}, {risk}, {health}, {contact})"
            )
            booth_number += 1

    lines.append(",\n".join(rows))
    lines += [
        "ON CONFLICT (constituency_id, booth_number) DO NOTHING;",
        "",
        "END;",
        "$$;",
        "",
        f"-- Total booths inserted: {booth_number - 1}",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(generate())
